### ISSUE TITLE
[BUG] Playback silence for formats 8kHz 16b/16b 1ch and 24kHz 16b/16b 1ch

### ISSUE THREAD

**Issue by zrombel** [thesofproject/sof#1650]
**Description**
Issue concerns two audio formats:
- 8kHz 16b/16b 1ch
- 24kHz 16b/16b 1ch
For those formats there was a need of setting period_source and period_sink parameters in pipeline components at minimal value of 4. 

After commit 528c72baefa299dd46f593f91246ac7f76c3047a there are two issues:

1) Silent samples at the beginning of playback on pipeline HOST -> BUF -> DAI
![image](https://user-images.githubusercontent.com/40820404/61455194-1b83f500-a963-11e9-91a4-a2022f757358.png)

2) Silence played on pipeline HOST -> BUF -> VOL -> BUF -> DAI
![image](https://user-images.githubusercontent.com/40820404/61455248-4b32fd00-a963-11e9-9ba1-a9cae94fcfb2.png)

**Reproduction Rate**
Always

**Environment**
1) Branch master commit 528c72baefa299dd46f593f91246ac7f76c3047a and later 
2) Bug concerns all platforms

**Comment by bkokoszx** [comment]
In our current flow of propagating prepare across the simple pipeline (HOST->DAI) we have respectively:
1. host_params()
2. dai_params().
Both of this functions invoke buffer_set_size function on the same buffer. In host_params() we perform buffer alignment to 32 B (for above format and period=4 buffer size is equal ALIGN_UP_32B(8 * 2B) * 4 = 128B). On the other hand in dai_params() we do not have any buffer alignment (buffer size is equal to 8 * 2 * 4 = 64B). Difference in buffer size calculation provides a mismatch, which is a root cause of this issue.

In my opinion we can perform similar buffer alignment on dai side. Additionally we should not allow other components like volume in comp_prepare() change sink buffer size if sink component is connected to dai (only check if sink buffer size is sufficient). Here is an example: 
https://github.com/bkokoszx/sof/commits/dw-dma-buffer-alignment

@juimonen 
What's your opinion?

**Comment by zrombel** [comment]
@bkokoszx changes fixes this bug. I have checked it with pass-trough pipelines, pipelines with volume and mixer, so it should be merged into master.
