### ISSUE TITLE
[FEATURE] Add support for uint64_t in sof-logger

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof#2775]
**Is your feature request related to a problem? Please describe.**

We need to be able to log 64bit variables. 
```
uint64_t var;
trace_error(%I64d\n", var);
trace_error("%I64x\n", var);
```

First we will need to understand how intrusive the changes are, how hard is to implement this and if it is worth it.
For now we can always workaround this issues by printing upper and lower 32bits.

**Comment by dbaluta** [comment]
Cc: @IulianOlaru249  @ymdatta @crazoes  feel free to look at this if you have some time. Just let a comment here so there won't be duplicate work.

**Comment by ymdatta** [comment]
@dbaluta : I would like to work on this, can you assign it to me? Thanks.

**Comment by paulstelian97** [comment]
It will be a major logger ABI change because the actual structures of the log messages will change -- the 4 parameter fields have to be changed from 32-bit integers to 64-bit integers and sof-logger has to be updated as well (which might prove tricky due to how 64-bit variables are passed on the stack differently from all others -- 16-bit and 8-bit integers are passed like 32-bit integers but 64-bit ones are different).

**Comment by nayakaj** [comment]
hi
i'm new here can you help me to solve

**Comment by dbaluta** [comment]
@nayakaj  just start with a simple tr_info call for example. Understand how that works first and then add support for 64 bits.

**Comment by marc-hb** [comment]
The sof-logger is being deprecated, I think this should be closed.

**Comment by paulstelian97** [comment]
> The sof-logger is being deprecated, I think this should be closed.

What are we using instead of it now?

**Comment by lgirdwood** [comment]
@paulstelian97 trace/logging tools are in transition now to be fully Zephyr-ized. Good news is that there is a bunch of nice Zephyr tools (that do work with 64bits) bad news is that we have not completed the Zephyr log integration as of today. It's still WIP with target of v2.3
