### ISSUE TITLE
Is DYNAMIC_INTERRUPTS mandatory in the sof system? 

### ISSUE THREAD

**Issue by hongshui3000** [thesofproject/sof#4044]
Is DYNAMIC_INTERRUPTS mandatory in the sof system?
I plan to call the sof library in zephyr, maybe my soc does not support dynamic interrupt.
What is the reason for the need for dynamic interrupt enable in sof? 

If CONFIG_LIBRARY is enabled, is it necessary to enable dynamic interrupts?

file : modules\audio\sof\zephyr\wrapper.c
```
/* Confirm Zephyr config settings - TODO: Use ASSERT */
#if !CONFIG_DYNAMIC_INTERRUPTS
#error Define CONFIG_DYNAMIC_INTERRUPTS
#endif
```

**Comment by lyakh** [comment]
@hongshui3000 the reason is that SOF requests interrupts dynamically, so, there isn't much point in not having them enabled with SOF. However, I guess, we could do something like #4063 . Note, that's a draft PR for now, let's see if others like it too or if you'd prefer to enable dynamic interrupt support for your platform.

**Comment by dbaluta** [comment]
I think we need something like this with i.MX also.

Cc: @iuliana-prodan

**Comment by iuliana-prodan** [comment]
> I think we need something like this with i.MX also.
> 
> Cc: @iuliana-prodan

DYNAMIC_INTERRUPTS are not imx specific, but they are required by SOF. So, we should enable them.

**Comment by lgirdwood** [comment]
TBH, dynamic irqs can probably be deprecated once Zephyr is fully integrated and we use the static Zephyr model. Its a simplification for us.

**Comment by hongshui3000** [comment]
The PR has been accepted and should be closed
