### ISSUE TITLE
[SOF] sof/script/run-mocks.sh with error

### ISSUE THREAD

**Issue by bawanqin1987** [thesofproject/sof#5098]
**Describe the bug**
when we wanna run ./modules/audio/sof/scripts/run-mocks.sh with ZEPHYR_WORK_SPACE for testting cmock ut case.
1.config the SOF as below,BUILD_UNIT_TESTS=ON,BUILD_UNIT_TESTS_HOST=OFF
![企业微信截图_1639646917828](https://user-images.githubusercontent.com/80995796/146344864-944691ef-e103-430f-be9a-ef164475649f.png)

2.and run the sh,there is error:
![企业微信截图_16396471027442](https://user-images.githubusercontent.com/80995796/146345385-498e9861-fc47-4b3c-bdca-4b2d245e4317.png)
show xt-xcc is unknown.but i had already define the xtensa toolchain path.

**Expected behavior**
it's ok to test pass

**Impact**
i can not use the xt-xcc ut case with simulation

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {ZEPHYR OS}
    * SOF: {run with hifi4}
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {PLATFORM}

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by bawanqin1987** [comment]
and then ,when i ON the BUILD_UNIT_TESTS_HOST,and the test ok.
i check the log,it's use local gcc,but it's not xt-xcc

**Comment by bawanqin1987** [comment]
yes,i had already install the hifi4 xtensa toolchain:
![企业微信截图_16396506319003](https://user-images.githubusercontent.com/80995796/146354941-a5c564db-9a78-4311-8ca9-fd3b2b898cd4.png)

because i use the the xtensa_build_zephyr.sh is ok to build
![企业微信截图_16396507273947](https://user-images.githubusercontent.com/80995796/146355240-7b7955f7-55b1-416b-bc00-5569f163aeb0.png)

**Comment by bawanqin1987** [comment]
i check the run_cmock sh and xtensa_build_all.sh ,The environment Settings are the same
![企业微信截图_16396509396534](https://user-images.githubusercontent.com/80995796/146355741-8e1585a2-d0fc-4464-9633-afee577200a4.png)

**Comment by bawanqin1987** [comment]
Failed to compile here, but wonder why show config failed  
![企业微信截图_16396519046386](https://user-images.githubusercontent.com/80995796/146358332-7eabdcb2-7a59-43a9-b250-437d7ea55e95.png)

**Comment by bawanqin1987** [comment]
and i check the process,sof build cmock with host and xtensa supported,you can check the process.
They all have macros to control them
native compiler and toolchain compiler also supported.

**Comment by bawanqin1987** [comment]
i set the PATH with my run cmock.sh,as below:
![企业微信截图_16396535877261](https://user-images.githubusercontent.com/80995796/146362464-148ebc1c-0362-46f5-a266-0bc98208abd7.png)
and run the shell:
![企业微信截图_16396536504344](https://user-images.githubusercontent.com/80995796/146362616-28861984-5e37-431a-bc95-3a1b7e2bad65.png)

why the process dual with xt-gcc,i can not set this tool.

**Comment by bawanqin1987** [comment]
ok, and i modify the run cmock -D
![企业微信截图_1639654645114](https://user-images.githubusercontent.com/80995796/146364901-669fddb7-2e7d-4d13-9071-e26f66369832.png)

and check the compile log:
![企业微信截图_16396547085935](https://user-images.githubusercontent.com/80995796/146365046-0582fed8-cec4-4299-85ef-a49b91755cad.png)

but there some files report error,I suspect that files compiled with XT-XCC do not match precompiled data such as file data types  
![企业微信截图_16396548129762](https://user-images.githubusercontent.com/80995796/146365283-3115ca28-8549-4fde-8f7e-d5f5e0890bbb.png)

**Comment by lgirdwood** [comment]
@bawanqin1987 can you try and update the SOF module to the latest HEAD.
We will need to wait for @marc-hb to comment here on the configuration required to use XT toolchain.

**Comment by marc-hb** [comment]
This bug is really too confusing, please close it and file a new, clearer and simpler bug if needed (probably not).

- Don't use screenshots, use copy/paste. Screenshots are not searchable and not indexed and they block copy/paste of your commands which is required to reproduce your issue.
 
- Copy/paste only the relevant bits.

- If you make code changes, at the very least share your modifications in a github branch or if it's very small copy/paste the git diff. We don't have time to scrutinize your screenshots to identify what you changed. The branch does not have to be pull request. There are of course exceptions but in general code changes that have not been reviewed are not supported.

- Describe one and only problem and failure per issue. There are 8 comments and each one seem to describe some different experiment.

- When reporting a bug, provide the exact and complete sequence of instructions that will other people absolutely sure they can reproduce the exact same error. No guessing.

- What is ZEPHYR_WORK_SPACE and what has it to do with any of this?


- These wrapper scripts provide default CMake parameters. If you need different CMake parameters it's often simpler NOT to use the wrapper script at all and invoke CMake directly.

- Finally, there is AFAIK is no wrapper script to run unit tests with the xtensa toolchain. To run unit tests with the xtensa toolchain, do not use any wrapper script and follow the official documentation: https://thesofproject.github.io/latest/developer_guides/unit_tests.html


http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by bawanqin1987** [comment]
ok  ,i  submit another case for you
