### ISSUE TITLE
4ch 16-bit DMIC recording for v0.55 has dc at the beginning of recording

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#686]
Please find the recorded sample here: https://drive.google.com/file/d/1Oz6uWxcdCedkXCkLsj-Z6iCWnx1zL8xE/view?usp=sharing

Recorded on GLK chromebook

**Comment by singalsu** [comment]
Here's a plot of the captured waveform

![issue_686](https://user-images.githubusercontent.com/28754793/49719833-f1e54b80-fc66-11e8-86ad-87ee1548047d.png)

The channels 1 and 2 look normal to me. Channels 3 and 4 with apparently no microphones contain a DC value of about -0.48 once the DCCOMP in HW and gain ramp controlled by FW is settled.

The tonal sound heard in the beginning is from the DCCOMP vs. gain ramp update caused "sawtooth" waveform. Since the non-connected microphones need to be removed by the audio framework I don't consider it as issue. The DCCOMP can compensate only about half of full scale DC level and the remaining DC level is what's seen after 300 ms time.
 
![issue_686_zoom1](https://user-images.githubusercontent.com/28754793/49720178-cf9ffd80-fc67-11e8-8dac-636478d70b66.png)

If the channels 3-4 are omitted, the start of channels 1-2 looks normal to me. I don't see any excessive DC level there. Can you please confirm if the bug is about channels 3-4.

![issue_686_zoom2](https://user-images.githubusercontent.com/28754793/49720584-dda24e00-fc68-11e8-8c7c-28dcc9485877.png)

What's strange here is that channels 1 and 2 seem to be identical except one LSB difference in the very beginning. The next plot is ch1 minus ch2.

![issue_686_ch12diff](https://user-images.githubusercontent.com/28754793/49720701-2f4ad880-fc69-11e8-95c6-4ad130ddbbac.png)

Unless your device has only one microphone it's a severe bug somewhere. Can you please confirm the number of microphones.

**Comment by ranj063** [comment]
@singalsu My recording was on a board with only one mic.

But according to Naveen the issue still persists when he checked with a board that has 2 mic's. He will send out an email to you

**Comment by singalsu** [comment]
@ranj063 The issue doesn't look like a bug in SOF. Maybe we can close this?

**Comment by naveen-manohar** [comment]
Can you please recheck with the captured file from UI ?

[myRecording02.zip](https://github.com/thesofproject/sof/files/2670917/myRecording02.zip)

**Comment by singalsu** [comment]
It looks and sounds quite OK but there's some strange tonal background noise. Is there a fan in the device or is the lab space noisy? Are the click sounds from keyboard typing?

There's no DC problems seen, so the this topic can be closed. But if there's no fan and the space where you tested was silent you may want to open another issue about noise. 

Generally microphones should be tested in silent condition and it would be good if you could in addition playback a chirp / sine sweep from about 100 Hz to 20 kHz via some high quality speaker (maybe a good over-ear headphone very near to microphone can be used too for output) . Audacity can make a chirp waveform via menu Generate -> Chirp.

**Comment by singalsu** [comment]
@naveen-manohar Can we close this issue?

**Comment by naveen-manohar** [comment]
Sure Seppo. Thanks for detailed explanation and follow-up.
We can close this for now.

Regarding BG noise - You are right, there was a fan in the lab.
Thanks fro the tip on Chirp wave generation.

**Comment by wenqingfu** [comment]
> Regarding BG noise - You are right, there was a fan in the lab.

@singalsu  :sweat_smile:

**Comment by singalsu** [comment]
Excellent, I'll close this. @wenqingfu Yep, exactly!
