### ISSUE TITLE
[FEATURE] Move rimage toml config files to SOF repository

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#7270]
**Is your feature request related to a problem? Please describe.**
The toml files in sof/rimage/config/*.toml have recently started covered properties of SOF modules that are no longer static properties of a platform, but rather are describiting attributes that can change when code is changed in SOF main. 

This highly problematic if a code to optimize a module's performance is merged to SOF main, a matching update is needed to rimage toml files (for all affected platforms), plus a separate sof/west.yml update to bring that in to SOF builds (with Zephyr where west is used).

**Describe the solution you'd like**
Rimage repository should only host the tool, not the actual platform-specific content.

**Describe alternatives you've considered**
Moving only IPC4 specific data is one option, but due to design of rimage, this seems rather complex and in the end the easier solution would be to move all of toml config files.

**Additional context**
- Recent rimage pull request history -> a sharp uptick in activity with IPC4 platforms:
https://github.com/thesofproject/rimage/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc
- https://github.com/thesofproject/sof/issues/8073

**Comment by lgirdwood** [comment]
@mwasko @marcinszkudlinski fyi - obvious effort reduction here to keep toml manifest configs alongside FW code.

**Comment by marc-hb** [comment]
> The toml files in sof/rimage/config/*.toml have recently started covered properties of SOF modules that are no longer static properties of a platform, but rather are describiting attributes that can change when code is changed in SOF main.

Wait: the static properties still exist AFAIK. So shouldn't rimage be able to read from more than one .toml file / from _both_ places? Would simply concatenating the files in the order given be enough?

**Comment by kv2019i** [comment]
@marc-hb wrote:
> Wait: the static properties still exist AFAIK. So shouldn't rimage be able to read from more than one .toml file / from _both_ places? Would simply concatenating the files in the order given be enough? This would mean moving fewer files / less content 

But why should rimage (the tool) repo host even the static details? I agree we could split, but I'm not sure if there is any benefit to hosting in multiple repos. These are essentially the platforms we maintain in SOF repository. I.e. shouldn't rimage repo be more like a repo for gcc/clang in that it provides a tool that takes X in and spews Y out, but the input data X is hosted in other repos.

**Comment by marc-hb** [comment]
After taking a look at https://github.com/thesofproject/sof-docs/pull/451 I wonder why we're even building the extended manifest using C code in 2023?

https://github.com/thesofproject/rimage/issues?q=crash

AFAIK the extended manifest is merely concatenated to the "main" `.ri` rimage file, so they seem fairly independent from each other. So why stick to obsolete and crashing `rimage` "technology" for the extended manifest?

**Comment by pjdobrowolski** [comment]
I was just about closing my issue with crashing. Last changes in rimage improved significantly stability of that tool. @marc-hb I know that @aborisovich is huge advocate changing language of that tool but currently @softwarecki invest huge amount of work to make that tool a bit more bugfree. Soooo If you want to discuss future of that tool Andrey is right person ;)

**Comment by aborisovich** [comment]
@pjdobrowolski not exactly, I think I am actually the last person to discuss this with...
@mmaka1 convinced me that developing a tool that would replace rimage is pointless as rimage is perfectly fine and I should not waste time writing it.
* Arguments that rimage uses MSYS2 on Windows to provide gcc toolchain were repelled with "MSYS2 is perfectly fine".
* Arguments that C++ is a better language for such tools were also repelled that this is my personal preference and subjective opinion.
* Arguments that rimage lacks unit tests were also commented "just add them to rimage".
* Arguments that rimage uses OpenSSL installed by each developer individually on the system was also repelled with the fact that "in production image signing is carefully controlled, it does not matted what developers use locally".
* Ideas of reading .toml files from elf files dynamically that @softwarecki came with were also rejected as not needed.

So it looks  like rimage is here to stay since I'm very bad at making anyone "forcefully happy".
But yes, after @softwarecki fixes the tool stopped crashing on Windows and looks much more stable.

**Comment by lgirdwood** [comment]
> After taking a look at [thesofproject/sof-docs#451](https://github.com/thesofproject/sof-docs/pull/451) I wonder why we're even building the extended manifest using C code in 2023?

@marc-hb lets keep on topic. Verification of hashing/signing is faster in C and hence that's why rimage is in C today.

**Comment by softwarecki** [comment]
@lgirdwood I think @marc-hb was referring to the extended manifest created from toml files. It isn't signed, unlike the module manifest. So it can be generated by another tool and inserted at the beginning of the file.

For the toml files, I see the following problems with them:
- No support for file inclusion. We have a separate toml file for each platform. If a module is used by multiple platforms, we have an identical description of the module's capabilities/configuration duplicated in multiple files. A solution could be to separate module descriptions into separate files and include them in platform files.
- Lack of support for labels. At this moment, some fields of the module's conﬁguration is represented as hexadecimal bit masks that are completely unreadable by humans. Textual value labels should be introduced to make the configuration more readable.
- Enabling/disabling building of a given module requires correcting toml files.

My idea to solve these problems is to move the information from the toml files to the source code of the modules. While leaving in them only some basic description of the platform and its address space.
We can prepare a structure with the information necessary to generate the extended manifest and put it in a separate section of the elf file. It would be read by rimage (or any other tool in the future). In this way, we already provide some informations now. This is the module manifest (struct sof_man_module_manifest) in the ".module" section and the extended manifest (duplicated name, this is different information than in toml files), (struct ext_man_header) section ".fw_metadata". Module manifest for all modules we can easily move to source code, because its reading is already implemented in rimage. The ext_man_header structure was designed to be extensible, so it could be used to pass the module's pin configuration, etc. to rimage. The advantage of this approach is that rimage (or separate tool) would build all manifests using only a compilation artifacts. Adding/removing a module would not involve updating multiple toml files for different platforms.
When creating a loadable library, we eliminate the risk of taking a toml file that does not match the compiled module. The module metadata would be included in the module file.

**Comment by marc-hb** [comment]
> @lgirdwood I think @marc-hb was referring to the extended manifest created from toml files.

I was a bit vague but yes: the firmware manifest and the extended manifest are two very different problems and they seem to have a very simple and very clear line between them. The former has a limited scope and it is already implemented fully AFAIK whereas the extended manifest seems to be just getting started and currently "exploding" = why this PR was filed.

I haven't seen signing performance being an issue which means existing libraries in any other, high level and popular language could be re-used to avoid parsing, pushing bits and managing memory "by hand".

https://alexgaynor.net/2019/aug/12/introduction-to-memory-unsafety-for-vps-of-engineering/

> My idea to solve these problems is to move the information from the toml files to the source code of the modules...

These longer term ideas should probably be discussed in a new issue to keep this shorter-term PR "on topic". There is a convenient `... -> reference in new issue` button in the top-right corner of every comment.

**Comment by pjdobrowolski** [comment]
Moving rimage from one programing language to another is  simple in theory.  We had that discussion already last year and this year and it is not a "weekend" job.

**Comment by softwarecki** [comment]
https://github.com/thesofproject/sof/issues/7304

**Comment by lgirdwood** [comment]
@kv2019i can we build the module manifest 

> My idea to solve these problems is to move the information from the toml files to the source code of the modules. While leaving in them only some basic description of the platform and its address space.

@softwarecki  Ack - can we have an ELF section which can be looked up and the meta data can be parsed. i.e. the metadata is an array of objects all with a type and size header (allows it to be easily extended when required).

**Comment by kv2019i** [comment]
Note on tjhe Zephyr dependency we realized yesterday with @nashif . Zephyr depends on rimage and the static platform bits of toml files, to create bootable flash images. If we move the toml files, this creates an awkward dependency from Zephyr to SOF repo (i.e. to run low-level driver unit tests on hardware targets, Zephyr needs to depend on the high-level app code repository). 

One option is to duplicate the static bits (these don't change after all) of platform description in Zephyr repository (i.e. have subsets of the tomls files there), but ideally we should be able to share this configuration data and host the platform-specific bits e.g. in Zephyr (where the low-level code and drivers are anyways) from the audio application bits (audio modules, their properties and performance descriptions which are inherently linked to code in sof/src/audio).

**Comment by marc-hb** [comment]
> Note on tjhe Zephyr dependency we realized yesterday with @nashif .

I think you mean revert
- https://github.com/zephyrproject-rtos/zephyr/pull/56099

> These longer term ideas should probably be discussed in a new issue to keep this shorter-term PR "on topic".

Thanks @softwarecki for trying :-)

**Comment by lgirdwood** [comment]
Moved to v2.7 to give time to align with Zephyr

**Comment by kv2019i** [comment]
This probably needs some rimage work to allow rimage to process toml input from multiple separate files. This then allows to have base platform descriptions in rimage repository (or in Zephyr upstream), and move the algo-specific toml sections to SOF git.

**Comment by mengdonglin** [comment]
> This probably needs some rimage work to allow rimage to process toml input from multiple separate files. This then allows to have base platform descriptions in rimage repository (or in Zephyr upstream), and move the algo-specific toml sections to SOF git.

@kv2019i @lgirdwood @alex-cri , @aiChaoSONG will move the algo-specific toml sections to SOF git next month, good to move to v2.8?

**Comment by aiChaoSONG** [comment]
@kv2019i  Do we want a simple toml move(this is quick) or we also want to split platform config and algorithm config?

**Comment by lgirdwood** [comment]
@kv2019i ok, so v2.8 we need to do the topology and tooling split too.

**Comment by marc-hb** [comment]
Or much simpler; single repo for rimage and SOF:
- https://github.com/thesofproject/sof/issues/8178

**Comment by kv2019i** [comment]
Since my comment on August, discussion has spread out even more, so marking this as "unclear" for the moment.

**Comment by kv2019i** [comment]
Implemented with https://github.com/thesofproject/sof/pull/8297 , thanks @marc-hb !

**Comment by marc-hb** [comment]
Small zephyr doc update submitted, please review:
- https://github.com/zephyrproject-rtos/zephyr/pull/66307
