### ISSUE TITLE
Stopping/Pausing a CHAIN_DMA stream takes 100ms

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#8445]
Adding a Linux issue based on https://github.com/thesofproject/sof-test/pull/1126 comments

"ChainDMA enabled PCMs where the time to stop the stream takes more than 100ms (from trigger stop to PCM close)."

this needs to be root-caused, 100ms is not an acceptable response time.

@ujfalusi @lgirdwood we might transfer this issue to SOF at some point.

**Comment by plbossart** [comment]
nice work @ujfalusi. The response time should not depend on the number of active CHAIN_DMA streams, that's a code flow problem clearly.

**Comment by marc-hb** [comment]
There was one failure in daily tests with commit 1bd9e0d2c7a853d4c9, right before the #8451 fix was merged:
34373?model=TGLU_UP_HDA-ipc4&testcase=multiple-pause-resume-50

This failure was extremely rare. Rather than letting GitHub's auto-close this issue (anti--feature https://github.com/orgs/community/discussions/23476), let's make sure it does not happen for about a week and only then close it.

**Comment by plbossart** [comment]
@marc-hb @kv2019i  I don't think this issue should remain open, no one has reported any updated in 8+ months.
